### PR TITLE
Added my name Aman

### PR DESCRIPTION
**Pull request by gh0ulslayer**
Added my name Aman to contributors folder

### CODE REVIEW

**Comment by banrovegrie** [comment]
From Sweden with love.

**Comment by kjain1810** [comment]
Aman or Aman Aman?

**Comment by siddhant2001** [comment]
or aman (aman) aman?

**Comment by gh0ulslayer** [comment]
> Aman or Aman Aman?

Aman Aman Aman

**Comment by banrovegrie** [comment]
Maybe Aman Aman (Aman Aman)

**Pull request merged**
